### ISSUE TITLE
老哥咋运行呀

### ISSUE THREAD

**Issue by 1755799578** [314love/CyclingTour#1]
老哥add configurations那里你是咋设置的呀能发一下吗/(ㄒoㄒ)/

**Comment by 314love** [comment]
![image](https://github.com/314love/CyclingTour/assets/106265888/6232d8a9-a674-4ccc-a354-e0a7723f6c57)
![image](https://github.com/314love/CyclingTour/assets/106265888/421d8d22-7c5b-4ca6-9a5a-e8dda4eaf130)

**Comment by 314love** [comment]
这就是个基础的apringboot与vue项目，配置啥的都一样

**Comment by 1755799578** [comment]
> 这就是个基础的apringboot与vue项目，配置啥的都一样
谢谢老哥！！！！😙

**Comment by 1755799578** [comment]
老哥我为啥没有build and run呀。。要咋整
![Uploading 1.JPG…]()

**Comment by 1755799578** [comment]
![Uploading 1.JPG…]()

**Comment by 1755799578** [comment]
![Uploading 1.JPG…]()

**Comment by 314love** [comment]
加我qq
简介上有

**Comment by 1755799578** [comment]
> 加我qq 简介上有

加了老哥
